### ISSUE TITLE
[BUG] Weapon license with a different police script

### ISSUE THREAD

**Issue by Ghostgod131** [qbcore-framework/qb-cityhall#108]
I have a qbcore server and I have  Changed the qb-police to wasabi-police but when I Issue a weapon licence and they go to city hall they  Weapon licence is not there.
 Is there something I need to change in thidescript and if so can someone please help me and where I need to change it?

**Comment by GhostGod13** [comment]
im still having issues with qb-cityhall as it doesn't work with wasabi-police 

does anyone know how to fix it

**Comment by JB8099** [comment]
check qb-core/ config under licenses.

**Comment by solemanryan** [comment]
have qb-policejob default and still have that issue.

**Comment by Ghostgod131** [comment]
No it all works but when I change it to wasabi-police it stops work and I
can find the config to fix the licence issue I'm having.

**Comment by GhzGarage** [comment]
https://discord.gg/qbcore
