### ISSUE TITLE
[BUG] Setjob function not working

### ISSUE THREAD

**Issue by Fleaket** [qbcore-framework/qb-cityhall#109]
When I go to apply for a job via the NPC at city hall, like taxi for example, no notification comes up and I don't get the job. There are no errors in F8 and console. The jobs do exist. Not sure what else to do. Thank you for your help in advance!

**Comment by Pewwww53** [comment]
Can you tell or show the errors in console and f8?

**Comment by Fleaket** [comment]
> Can you tell or show the errors in console and f8?

As I said, there are no errors
