### ISSUE TITLE
Issue with trying to purchase license once revoked

### ISSUE THREAD

**Issue by bakerzone** [qbcore-framework/qb-cityhall#12]
![Screenshot 2021-08-03 183117](https://user-images.githubusercontent.com/63113526/128060173-0e7ab94a-8b36-4004-96a6-2ff205b81513.png)

Hi,

I have found an issue with when you have had your license revoked and attempt to buy another then the attached is thrown.
Also when you go to the town hall there are no prompts to allow you to request to take a driving test.
If a license is revoked how do you ask for this back and should the police actually remove this from you?

Thanks in advance.

Angie

**Comment by Developer-Bear** [comment]
@bakerzone grab the latest updates to `qb-cityhall`, `qb-inventory`, and `qb-policejob` and try again. With this update police can `/grantlicense` and `/revokelicenses` 

Should also fix the errors. Let me know :)

**Comment by bakerzone** [comment]
Hiya,

I've updated all 3 scripts, think I missed that qb-policejob update as saw it in the notes after seeing your update.
The command is there, so I'm sure it'll work.

Many thanks for replying so quick and for making these scripts in the 1st place, an excellent job.

Thanks
Angie

**Comment by Developer-Bear** [comment]
Absolutely, thanks for your response!
