### ISSUE TITLE
undefinded license

### ISSUE THREAD

**Issue by thatsimpressive** [qbcore-framework/qb-cityhall#13]
This appears after receiving the weapons license - https://i.imgur.com/UYzSeD6.png

**Comment by ihyajb** [comment]
Could not reproduce the issue. Try updating all your scripts, weapons license has to do with multiple different scripts.

**Comment by Developer-Bear** [comment]
Tested on fresh build, could not reproduce issue.

**Comment by thatsimpressive** [comment]
Updated the addon to the latest version, and now the issue has been resolved.

**Comment by ihyajb** [comment]
if the issue has been solved please close this so it can be moved to the right category. Thank you
