### ISSUE TITLE
DMV

### ISSUE THREAD

**Issue by includes08** [qbcore-framework/qb-cityhall#21]
Is there a way to remove the default driving license and have the ability to give the license based on a dmv test? So basically a whitelist for a driving license given by the instructor?

**Comment by Synthethics** [comment]
The drivers license is a "starting item" that's added upon first spawn, along with an ID Card and a Phone. If you'd like to remove the standard drivers license that people get on first spawn, remove it from qb-core/shared.lua, Line 42. If you have any more issues please visit https://discord.gg/qbcore
