### ISSUE TITLE
Driver license 

### ISSUE THREAD

**Issue by Slay3rIQ** [qbcore-framework/qb-cityhall#26]
Can buy a driver license without driving test And theory. Set a notification that you are not allowed to buy a driver license without permission from the driving school boss.

**Comment by Synthethics** [comment]
There is currently no drivers school implemented. You get a drivers license by default once you create a character for the first time (Starting items in qb-core/shared.lua). If your license gets taken away, a police officer can grant you the license back the same as they were to grant you a weapons license.
