### ISSUE TITLE
"help wanted" weaponlicense

### ISSUE THREAD

**Issue by Maxryodric** [qbcore-framework/qb-cityhall#38]
Please help me, I do not understand how to get a "weaponlicense", the weapons store requires a license, I got a job as a policeman but I did not understand how to give it to the player or myself, I got a "weaponlicense" in the inventory with the "giveitem" command, but the store still asks for a license

**Comment by dexter9006** [comment]
/grantlicense with policejob, then take it from city hall

**Comment by Maxryodric** [comment]
> /grantlicense with policejob, then take it from city hall

Thank You
