### ISSUE TITLE
Free Licenses Glitch

### ISSUE THREAD

**Issue by Kirozai** [qbcore-framework/qb-cityhall#40]
if you have 0 cash on you , you can buy as much free licenses as you want and it doesn't even check for the bank .

**Comment by Yonatannn** [comment]
if you use this trigger:
Player.Functions.RemoveMoney
its check your money first and then remove the cash if you have..

**Comment by BerkieBb** [comment]
This is fixed with the [Overhaul PR](https://github.com/qbcore-framework/qb-cityhall/pull/43)
