### ISSUE TITLE
[Script Error]

### ISSUE THREAD

**Issue by erayko-dev** [qbcore-framework/qb-cityhall#45]
Hey, my core is updated but I'm getting this error, any help?:

![image](https://user-images.githubusercontent.com/76734458/161974632-ab56c227-19f3-406a-a794-265c49f8cec2.png)

**Comment by FildonPrime** [comment]
Hi @erayko-dev 
Please check inside the client directory of `qb-core` for `drawtext.lua` and let me know if it exists, 
A screenshot would be fine as well.

**Comment by erayko-dev** [comment]
Thanks for the response @FildonPrime !
It doesn't appear to be there:
![image](https://user-images.githubusercontent.com/76734458/162002813-5213a505-b4ed-46ca-81fe-971d68c0d65b.png)
