### ISSUE TITLE
html /app.js

### ISSUE THREAD

**Issue by next-game** [qbcore-framework/qb-cityhall#59]
I don't really understand scripts, but I'm learning, I added four jobs, everything was duplicated in the menu, I rummaged through the entire server, looked for where I did what wrong myself... I didn't find anything, finally replaced the html /app.js on the old one, everything worked fine

**Comment by next-game** [comment]
he duplicated from [qb]\qb-cityhall\server local availableJobs

**Comment by BerkieBb** [comment]
![image](https://user-images.githubusercontent.com/82737367/167673308-6a808064-ab72-4ceb-a954-bb12d4591f39.png)
This is what mine looks like after duplicating the ones and renaming them so they don't conflict

**Comment by BerkieBb** [comment]
You don't duplicate the table, only the entries

**Comment by next-game** [comment]
looked at the updated index.html, there is no longer a list of works, in my version it was in index.html
