### ISSUE TITLE
Email not Receive 

### ISSUE THREAD

**Issue by kaptenecha** [qbcore-framework/qb-cityhall#60]
![image](https://user-images.githubusercontent.com/3710291/166117881-30b90bff-651f-4d2e-9b56-503232887ed4.png)

after waiting around 10 mins
i didnt get any mail to take driving license
can someone help me? thanks

**Comment by nutter887** [comment]
me too!

**Comment by shadowTW** [comment]
you need to config it

**Comment by shadowTW** [comment]
config.lua -> Line 47,48,49

Put your citizen id there

**Comment by kaptenecha** [comment]
> config.lua -> Line 47,48,49
> 
> Put your citizen id there

thanks, for helping. shadow
