### ISSUE TITLE
[BUG] Relogging Breaks Job Page

### ISSUE THREAD

**Issue by Log1Xz** [qbcore-framework/qb-cityhall#91]
Script works all good for me until I relog, when I come back and talk to the NPC, the licenses page works but the jobs page is empty (more like it's hidden) and I can only see the back button.

**Comment by Log1Xz** [comment]
![image](https://user-images.githubusercontent.com/10688669/207954154-1a3b9ec2-2adc-44e1-863c-8f595b45419d.png)

**Comment by Bakisito** [comment]
tried to recreate the problem and could not find anything, everything working fine. fresh install qbcore

**Comment by ahmoge** [comment]
got the same issue
